### PR TITLE
Fix compatibility with Jackson's MappingIterator

### PR DESCRIPTION
**Pull request by lhotari**
- See #18

### CODE REVIEW

**Comment by travisbrown** [comment]
Thanks much for catching this. It looks like you'll need a type annotation for `objectMapper.reader()` to keep 2.5 happy. I'm not sure about the other failures—do you have any idea?

**Comment by lhotari** [comment]
@travisbrown I made a workaround for Jackson 2.5, not sure why it was happening. I had pushed an invalid test originally, I've now simplified the test and removed the assertion that was invalid since it's not relevant for testing the MappingIterator compatibility.

**Comment by travisbrown** [comment]
Excellent, thanks @lhotari! I'll release an 0.7.1 as soon as possible (I'm traveling today so that's likely to be tomorrow).

**Comment by lhotari** [comment]
Thank you @travisbrown, sounds great. Looking forward to the 0.7.1 release.

**Comment by lhotari** [comment]
Hi @travisbrown , when do you plan to release 0.7.1 ? Thanks

**Comment by travisbrown** [comment]
@lhotari I was thinking of going ahead and releasing an 0.8.0 for circe itself, but that probably won't happen this week, so I'll aim to get this published today.

**Comment by lhotari** [comment]
Thank you @travisbrown

**Comment by travisbrown** [comment]
@lhotari Okay, it's on its way to Maven Central—thanks again!

**Comment by lhotari** [comment]
:+1:

**Pull request merged**
