### PR TITLE
Make object mapper public

### PR DESCRIPTION
**Pull request by BenFradet**
I apparently need access to the circe-specific mapper to interface with other libraries.

### CODE REVIEW

**Comment by travisbrown** [comment]
:+1: from me.

**Comment by BenFradet** [comment]
Would it be possible to get a patch release incorporating this change?

**Comment by travisbrown** [comment]
@BenFradet Would you want to run the 0.11.1 release? I confirmed in #53 that it's binary compatible, and I can publish release notes later, but I'm traveling and don't have this machine set up to publish.

**Comment by BenFradet** [comment]
I would be happy to however I don't think I have the creds to be able to publish?

I'm having deja-vu with another circe project :thinking: , anyway it's not super urgent.

**Comment by travisbrown** [comment]
I'm running the release now. I thought you had published circe-fs2, @BenFradet? If you don't mind, can you give me your Sonatype username and I'll open a ticket.

**Comment by BenFradet** [comment]
Nope, but I think we already had this convo in circe-fs2 though, my sonatype username is `BenFradet` :+1:

**Comment by travisbrown** [comment]
@BenFradet Maybe it'll stick [this time](https://issues.sonatype.org/browse/OSSRH-17005?focusedCommentId=650912&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-650912). :smile:

**Pull request merged**
