### PR TITLE
Add a module for Jackson 2.13 and make the 212 module use Jackson 2.12

### PR DESCRIPTION
**Pull request by maxstreese**

### CODE REVIEW

**Comment by maxstreese** [comment]
This aims to fix #306

**Comment by RobertoUa** [comment]
is this going to be merged?

**Comment by maxstreese** [comment]
@zmccoy would you be able to take a look at this? I am unsure who the current maintainers of this project are since @travisbrown announced he would step back if I recall correctly? The reason for this PR is explained in #306. Let me know if I can assist in any way.

**Comment by zmccoy** [comment]
@maxstreese Hey, thanks for the PR and ping!  @zarthross and myself are currently trying to keep things tidy.  I'll give this a look!

**Review by zmccoy — APPROVED** [review]
One thing to note is that if anyone has switched to this and is using new functionality in the 213 module this will end up removing that from their classpath.  The remedy is of course to have them use the 213 module instead.

**Pull request merged**
